# Generated by Django 4.2.3 on 2023-08-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="login_date",
            field=models.DateTimeField(auto_now=True, verbose_name="登录时间"),
        ),
    ]
