# Generated by Django 4.2.3 on 2023-08-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_userinfo_login_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="login_date",
        ),
    ]
