# Generated by Django 4.2.3 on 2023-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, verbose_name="发送者邮箱")),
                ("content", models.TextField(verbose_name="发送的内容")),
            ],
            options={
                "verbose_name_plural": "邮件发送",
            },
        ),
    ]
